plugins {
    id 'java'
}

group 'com.vingame'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compile project(':VbeeCommon')
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
task copyJar(type: Copy) {
    from configurations.compile {
        include 'VbeeCommon*.jar'
    }
    into 'libs/'
}
build.dependsOn copyJar