version: '3.8'

services:
  gameplatform_vbee_api:
    image: bancodegame/gameplatform_vbee_api:v1.1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../../../game-logs/vbee_api:/app/logs
    networks:
      env-setup_mynetwork:
        ipv4_address: 10.5.0.8

networks:
  env-setup_mynetwork:
    external: true
