plugins {
    id 'java'
}

group 'com.vingame'
version ''

sourceCompatibility = 1.8
//buildDir = "../../../dist/build"
repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile project(':VinPlayUserCore')
    compile project(':VinPlayDAL')
    compile project(':VinPlayCardLib')
    compile project(':BitZeroMinigame')
    compile fileTree(excludes:['bz-allinone.jar'], dir: '../../libs', include: ['*.jar'])
}
task copyJar(type: Copy) {
    from configurations.compile {
        include  'VinPlayUserCore*.jar',  "VinPlayDAL*.jar",  "VinPlayCardLib*.jar",  "BitZeroMinigame*.jar", "VbeeCommon*.jar"
    }
    into 'libs/'
}
task copylibs(type: Copy) {
    from '../../libs'
    into 'libs'
}

copylibs.dependsOn copyJar
build.dependsOn copylibs
