/*
 * Decompiled with CFR 0.144.
 */
package game.modules.slot.cmd;

public class SlotCMD {
    public static final short SUBSCRIBE_HALL = 10001;
    public static final short UNSUBSCRIBE_HALL = 10002;
    public static final short UPDATE_JACKPOTS = 10003;
    public static final short LIST_AUTO_PLAY_INFO = 10004;
    public static final short PLAY_KHO_BAU = 2001;
    public static final short RESULT_KHO_BAU = 2001;
    public static final short UPDATE_POT_KHO_BAU = 2002;
    public static final short SUBSCRIBE_KHO_BAU = 2003;
    public static final short UNSUBSCRIBE_KHO_BAU = 2004;
    public static final short CHANGE_ROOM_KHO_BAU = 2005;
    public static final short AUTO_PLAY_KHO_BAU = 2006;
    public static final short STOP_PLAY_KHO_BAU = 2007;
    public static final short FORCE_STOP_PLAY_KHO_BAU = 2008;
    public static final short KHO_BAU_X2 = 2009;
    public static final short BIG_WIN_KHO_BAU = 2010;
    public static final short KHO_BAU_INFO = 2011;
    public static final short KHO_BAU_FREE_DAILY = 2012;
    public static final short KHO_BAU_MINIMIZE = 2013;
    public static final short KHO_BAU_RESULT_MINIMIZE = 2014;
    public static final short KHO_BAU_TOTAL_FREE_SPIN = 2015;
    public static final short PLAY_NU_DIEP_VIEN = 3001;
    public static final short UPDATE_POT_NU_DIEP_VIEN = 3002;
    public static final short SUBSCRIBE_NU_DIEP_VIEN = 3003;
    public static final short UNSUBSCRIBE_NU_DIEP_VIEN = 3004;
    public static final short CHANGE_ROOM_NU_DIEP_VIEN = 3005;
    public static final short AUTO_PLAY_NU_DIEP_VIEN = 3006;
    public static final short STOP_PLAY_NU_DIEP_VIEN = 3007;
    public static final short FORCE_STOP_PLAY_NU_DIEP_VIEN = 3008;
    public static final short NU_DIEP_VIEN_INFO = 3009;
    public static final short BIG_WIN_NU_DIEP_VIEN = 3010;
    public static final short NDV_FREE_DAILY = 3012;
    public static final short NDV_MINIMIZE = 3013;
    public static final short NDV_RESULT_MINIMIZE = 3014;
    public static final short PLAY_AVENGER = 4001;
    public static final short UPDATE_POT_AVENGER = 4002;
    public static final short SUBSCRIBE_AVENGER = 4003;
    public static final short UNSUBSCRIBE_AVENGER = 4004;
    public static final short CHANGE_ROOM_AVENGER = 4005;
    public static final short AUTO_PLAY_AVENGER = 4006;
    public static final short STOP_PLAY_AVENGER = 4007;
    public static final short FORCE_STOP_PLAY_AVENGER = 4008;
    public static final short AVENGER_INFO = 4009;
    public static final short BIG_WIN_AVENGER = 4010;
    public static final short AVENGERS_TOTAL_FREE_SPIN = 4011;
    public static final short AVENGER_FREE_DAILY = 4012;
    public static final short AVENGER_MINIMIZE = 4013;
    public static final short AVENGER_RESULT_MINIMIZE = 4014;
    public static final short PLAY_VQV = 5001;
    public static final short UPDATE_POT_VQV = 5002;
    public static final short SUBSCRIBE_VQV = 5003;
    public static final short UNSUBSCRIBE_VQV = 5004;
    public static final short CHANGE_ROOM_VQV = 5005;
    public static final short AUTO_PLAY_VQV = 5006;
    public static final short STOP_PLAY_VQV = 5007;
    public static final short FORCE_STOP_PLAY_VQV = 5008;
    public static final short VQV_X2 = 5009;
    public static final short BIG_WIN_VQV = 5010;
    public static final short VQV_INFO = 5009;
    public static final short VQV_FREE_DAILY = 5012;
    public static final short VQV_MINIMIZE = 5013;
    public static final short VQV_RESULT_MINIMIZE = 5014;
    // Spartan
    public static final short PLAY_SPARTAN = 10001;
    public static final short UPDATE_POT_SPARTAN = 10002;
    public static final short SUBSCRIBE_SPARTAN = 10003;
    public static final short UNSUBSCRIBE_SPARTAN = 10004;
    public static final short CHANGE_ROOM_SPARTAN = 10005;
    public static final short AUTO_PLAY_SPARTAN = 10006;
    public static final short STOP_PLAY_SPARTAN = 10007;
    public static final short FORCE_STOP_PLAY_SPARTAN = 10008;
    public static final short SPARTAN_INFO = 10009;
    public static final short BIG_WIN_SPARTAN = 10010;
    public static final short SPARTANS_TOTAL_FREE_SPIN = 10011;
    public static final short SPARTAN_FREE_DAILY = 10012;
    public static final short SPARTAN_MINIMIZE = 10013;
    public static final short SPARTAN_RESULT_MINIMIZE = 10014;
    // Audition
    public static final short PLAY_AUDITION = 11001;
    public static final short UPDATE_POT_AUDITION = 11002;
    public static final short SUBSCRIBE_AUDITION = 11003;
    public static final short UNSUBSCRIBE_AUDITION = 11004;
    public static final short CHANGE_ROOM_AUDITION = 11005;
    public static final short AUTO_PLAY_AUDITION = 11006;
    public static final short STOP_PLAY_AUDITION = 11007;
    public static final short FORCE_STOP_PLAY_AUDITION = 11008;
    public static final short AUDITION_INFO = 11009;
    public static final short BIG_WIN_AUDITION = 11010;
    public static final short AUDITION_FREE_DAILY = 11012;
    public static final short AUDITION_MINIMIZE = 11013;
    public static final short AUDITION_RESULT_MINIMIZE = 11014;
    // SamTruyen
    public static final short PLAY_SAMTRUYEN = 12001;
    public static final short UPDATE_POT_SAMTRUYEN = 12002;
    public static final short SUBSCRIBE_SAMTRUYEN = 12003;
    public static final short UNSUBSCRIBE_SAMTRUYEN = 12004;
    public static final short CHANGE_ROOM_SAMTRUYEN = 12005;
    public static final short AUTO_PLAY_SAMTRUYEN = 12006;
    public static final short STOP_PLAY_SAMTRUYEN = 12007;
    public static final short FORCE_STOP_PLAY_SAMTRUYEN = 12008;
    public static final short SAMTRUYEN_INFO = 12009;
    public static final short BIG_WIN_SAMTRUYEN = 12010;
    public static final short SAMTRUYEN_TOTAL_FREE_SPIN = 12011;
    public static final short SAMTRUYEN_FREE_DAILY = 12012;
    public static final short SAMTRUYEN_MINIMIZE = 12013;
    public static final short SAMTRUYEN_RESULT_MINIMIZE = 12014;


    public static final short PLAY_RANGE_ROVER= 13001;
    public static final short UPDATE_POT_RANGE_ROVER= 13002;
    public static final short SUBSCRIBE_RANGE_ROVER= 13003;
    public static final short UNSUBSCRIBE_RANGE_ROVER= 13004;
    public static final short CHANGE_ROOM_RANGE_ROVER= 13005;
    public static final short AUTO_PLAY_RANGE_ROVER= 13006;
    public static final short STOP_PLAY_RANGE_ROVER= 13007;
    public static final short FORCE_STOP_PLAY_RANGE_ROVER= 13008;
    public static final short RANGE_ROVER_X2 = 13009;
    public static final short BIG_WIN_RANGE_ROVER= 13010;
    public static final short RANGE_ROVER_INFO = 13001;
    public static final short RANGE_ROVER_FREE_DAILY = 13012;
    public static final short RANGE_ROVER_MINIMIZE = 13013;
    public static final short RANGE_ROVER_RESULT_MINIMIZE = 13014;
    public static final short RANGE_ROVER_TOTAL_FREE_SPIN = 13015;
}

