rootProject.name = 'BackendV2'
include 'VbeeCommon'
include 'VBeeSecurity'
include 'VinPlayCardLib'
include 'VinPlayDAL'
include 'VinPlayUserCore'
include 'cotuong'
include 'BitzeroAll'
include 'BitZeroMinigame'
include 'CardCoreLib'
include 'game:baicao'
findProject(':game:baicao')?.name = 'baicao'
include 'game:cotuong'
findProject(':game:cotuong')?.name = 'cotuong'
include 'game:cotuong'
findProject(':game:cotuong')?.name = 'cotuong'
include 'game:bacayServer'
findProject(':game:bacayServer')?.name = 'bacayServer'
include 'game:binh'
findProject(':game:binh')?.name = 'binh'
//include 'game:caro'
//findProject(':game:caro')?.name = 'caro'
include 'game:lieng'
findProject(':game:lieng')?.name = 'lieng'
include 'game:Minigame'
findProject(':game:Minigame')?.name = 'Minigame'
include 'game:OverUnder'
findProject(':game:OverUnder')?.name = 'OverUnder'
include 'game:poker'
findProject(':game:poker')?.name = 'poker'
//include 'game:pokertour'
//findProject(':game:pokertour')?.name = 'pokertour'
include 'game:sam'
findProject(':game:sam')?.name = 'sam'
include 'game:slot'
findProject(':game:slot')?.name = 'SlotMachine'
include 'game:tlmn'
findProject(':game:tlmn')?.name = 'tlmn'
include 'game:xidzach'
findProject(':game:xidzach')?.name = 'xidzach'
include 'game:xocdia'
findProject(':game:xocdia')?.name = 'xocdia'
include 'api:VinPlayBackend'
findProject(':api:VinPlayBackend')?.name = 'VinPlayBackend'
include 'api:VinPlayPortal'
findProject(':api:VinPlayPortal')?.name = 'VinPlayPortal'
include 'api:wspay'
findProject(':api:wspay')?.name = 'wspay'
include 'api:vbee'
findProject(':api:vbee')?.name = 'vbee'
include 'game:xizach'
findProject(':game:xizach')?.name = 'xizach'
include 'game:banca'
findProject(':game:banca')?.name = 'banca'
include 'game:slot3x3'
findProject(':game:slot3x3')?.name = 'slot3x3'
include 'game:kendo'
findProject(':game:kendo')?.name = 'kendo'
//include 'game:slot_old'
//findProject(':game:slot_old')?.name = 'slot_old'
include 'CommonTool'
include 'CommonTool'
include 'ClearCache'
include 'TestProject'
include 'game:baucua'
findProject(':game:baucua')?.name = 'baucua'
include 'game:baucuato2'
findProject(':game:baucuato2')?.name = 'baucuato2'
include 'api:wsreport'
findProject(':api:wsreport')?.name = 'wsreport'
include 'game:taixiuMini'
findProject(':game:taixiuMini')?.name = 'taixiuMini'
include 'game:taixiuMd5'
findProject(':game:taixiuMd5')?.name = 'taixiuMd5'

