plugins {
    id 'java'
}

group 'com.vingame'
version ''

sourceCompatibility = 1.8
//buildDir = "../../../dist/build"
repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile project(':VinPlayUserCore')
    compile project(':VinPlayDAL')
    compile project(':VinPlayCardLib')
    compile project(':BitZeroMinigame')
    compile fileTree(include: ['*.jar'], dir: '../../libs', exclude: 'bz-allinone.jar')
    // https://mvnrepository.com/artifact/org.java-websocket/Java-WebSocket
    implementation group: 'org.java-websocket', name: 'Java-WebSocket', version: '1.5.7'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'

}
task copyJar(type: Copy) {
    from configurations.compile {
        include  'VinPlayUserCore*.jar',  "VinPlayDAL*.jar",  "VinPlayCardLib*.jar",  "BitZeroMinigame*.jar"
    }
    into 'libs/'
}

task copylibs(type: Copy) {
    from '../../libs'
    into 'libs'
}

copylibs.dependsOn copyJar
build.dependsOn copylibs
