plugins {
    id 'java'
}

group 'com.vingame'
version ''

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

//buildDir = "../../../dist/build"
//jar {
//    dependsOn 'test'
//    archiveName = "bacay.jar"
//    from {
//        configurations.runtime.collect {
//            it.isDirectory() ? it : zipTree(it)
//        }
//
//        configurations.compile.collect {
//            it.isDirectory() ? it : zipTree(it)
//        }
//    }
//
//    manifest {
//        attributes 'Main-Class': 'game.bacay.server.BaCayGameServer'
//    }
//
//    exclude 'META-INF/*.RSA', 'META-INF/*.SF','META-INF/*.DSA'
//}
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile project(':VinPlayUserCore')
    compile project(':BitzeroAll')
    compile project(':CardCoreLib')
    compile fileTree(include: ['*.jar'], dir: '../../libs')
}
task copyJar(type: Copy) {
    from configurations.compile {
        include  'VinPlayUserCore*.jar',  "BitzeroAll*.jar",  "CardCoreLib*.jar", "VbeeCommon*.jar"
    }
    into 'libs/'
}
task copylibs(type: Copy) {
    from '../../libs'
    into 'libs'
}

copylibs.dependsOn copyJar
build.dependsOn copylibs

