server.port=8087
redis.host=redis://45.76.178.154:6379

#Mongo
spring.data.mongodb.host=45.76.178.154
spring.data.mongodb.port=27017
spring.data.mongodb.database=win123club
spring.data.mongodb.auth_database=admin
spring.data.mongodb.username=admin
spring.data.mongodb.password=Linh742@ASdfH