server.port=8087
redis.host=redis://10.40.112.3:6379

#Mongo
spring.data.mongodb.host=10.40.112.3
spring.data.mongodb.port=27017
spring.data.mongodb.database=win123club
spring.data.mongodb.auth_database=admin
spring.data.mongodb.username=admin
spring.data.mongodb.password=Linh742@ASdfH

#Countries are allowed to access hot updates
hotupdate.allowed.countries=VNM,KMM
hotupdate.rejected.countries=USA,SG