plugins {
    id 'java'
}

group 'com.vingame'
version ''

sourceCompatibility = 1.8
repositories {
    mavenCentral()
}
buildDir = "../build"
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile project(':VbeeCommon')
    compile project(':BitzeroAll')
    compile fileTree(include: ['*.jar'], dir: '../libs')
    // https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp
    implementation group: 'com.squareup.okhttp3', name: 'okhttp', version: '3.14.9'
    implementation ('io.socket:socket.io-client:1.0.1')
}
